version: "3.9"

services:
  backend:
    build:
      context: back_end
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - myapp-network
    environment:
      - PORT=5000
      - SECRET_TOKEN=a87b9e6b74cf50873023890d11b8d2dffc9a230b7ad614ebf2b3a12b8f462db1
      - DB_HOST=localhost
      # - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=test_db
      - DB_PORT=5432

  frontend:
    build:
      context: front_end
      dockerfile: Dockerfile
      
    env_file:
      - front_end/.env
    container_name: frontend

    ports:
      - "3000:3000"
    networks:
      - myapp-network
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5000
    depends_on:
      - backend

networks:
  myapp-network:
    driver: bridge
