version: "3.9"

services:
  backend:
    build:
      context: back_end
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - back_end/.env
    ports:
      - "5000:5000"
    networks:
      - myapp-network

  frontend:
    build:
      context: front_end
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - front_end/.env.local
    ports:
      - "3333:3333"
    depends_on:
      - backend
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
